import "@/styles/index.scss";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/charts/styles.css";
import '@mantine/tiptap/styles.css';
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Roboto } from "next/font/google";
import { Suspense } from "react";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import Script from "next/script";
import Providers from "@/lib/ui/providers/Providers";

export const metadata: Metadata = {
  title: "NextjsDemo",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme=""
      className={`${poppins.className} ${roboto.className}`}
      {...mantineHtmlProps}
    >
      <head>
        <Suspense>
          <Script strategy="beforeInteractive" src="/js/setThemeScript.js" />
          <ColorSchemeScript />
        </Suspense>
      </head>
      <body>
        <Providers>
          {children}
          <Notifications autoClose={3000} />
        </Providers>
      </body>
    </html>
  );
}
